const cartTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  INCREASE_AMOUNT: "INCREASE_AMOUNT",
  DECREASE_AMOUNT: "DECREASE_AMOUNT",
  SHOW_CART: "SHOW_CART",
  HIDE_CART: "HIDE_CART",
};

export default cartTypes;
