const cartTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  INCREASE_AMOUNT: "INCREASE_AMOUNT",
  DECREASE_AMOUNT: "DECREASE_AMOUNT",
  CHECK_OUT: "CHECK_OUT",
  SHOW_CART: "SHOW_CART",
  HIDE_CART: "HIDE_CART",
  SHOW_LOADING: "SHOW_LOADING",
  HIDE_LOADING: "HIDE_LOADING",
};

export default cartTypes;
