const productsTypes = {
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_ERROR: "FETCH_PRODUCTS_ERROS",
  ADD_FILTER: "ADD_FILTER",
  REMOVE_FILTER: "REMOVE_FILTER",
  CHANGE_FILTER_TYPE: "CHANGE_FILTER_TYPE",
  CLEAR_FILTERS: "CLEAR_FILTERS",
  RESET_STARTER: "RESET_STARTER",
};

export default productsTypes;
